[theme]
primaryColor = "#39605a"
backgroundColor = "#e3c5aa"
secondaryBackgroundColor = "rgba(255, 255, 255, 0.9)"
textColor = "#4e4e4e"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false